name: youtube-playlist-downloader
version: 0.1.0.0
description: A simple YouTube playlist downloader using yt-dlp

dependencies:
  - base >= 4.7 && < 5
  - process
  - optparse-applicative
  - brick >= 2.1.1
  - vty
  - vty-unix
  - text
  - vector
  - aeson >=2.1.2.1
  - bytestring
  - mtl
  - microlens >= 0.4.13

library:
  source-dirs: src
  exposed-modules:
    - CommandLineParsing
    - Parser
    - Types
    - UI
    - UI.Types
    - UI.ListView
    - UI.DetailsView
    - UI.MenuPanel
    - YT

executables:
  youtube-playlist-downloader:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -Wall
      - -threaded
    other-modules:
      - Paths_youtube_playlist_downloader
      - CommandLineParsing
      - Parser
      - Types
      - UI
      - UI.DetailsView
      - UI.ListView
      - UI.MenuPanel
      - UI.Types
      - YT

tests:
  allTests:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -Wall
    dependencies:
      - base >= 4.7 && < 5
      - hspec >= 2.11.10
      - hspec-discover >= 2.11.10
      - youtube-playlist-downloader